### ISSUE TITLE
Disable Branch Protection

### ISSUE THREAD

**Issue by SulpherStaer** [eosfrontier/plotball_launcher#24]
This app is not yet live, branch protection is not required, and the programmer has requested it to be disabled for now.

**Comment by WafflesMcDuff** [comment]
@rolf-yoast / @IreneSchuit  - I've turned off the need for Pull Request Reviews. 
I'd still prefer to keep doing PRs so that you can squash your commits and keep the commit history clean.
Is that good enough?

**Comment by WafflesMcDuff** [comment]
I'm going to assume after 26 days that this issue is resolved.
